name: Publish release APK

# Controls when the action will run.
on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     tags:
#       - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package-release-apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v3
      
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generate signed APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign APK with keystore
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: ./app/phone/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          alias: ${{ secrets.KEY_STORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASS }}
          keyPassword: ${{ secrets.KEY_STORE_PASS }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
          
      - uses: jungwinter/split@v1
        id: signed_files
        with:
          msg: ${{ steps.sign_app.outputs.signedReleaseFiles }}
          separator: ':'

      - name: Upload release APK
        uses: actions/upload-artifact@v2
        with:
#           name: app-release.apk
          path: |
            ${{ steps.signed_files._0 }}
            ${{ steps.signed_files._1 }}
            ${{ steps.signed_files._2 }}
            ${{ steps.signed_files._3 }}
            ${{ steps.signed_files._4 }}
#         ${{steps.sign_app.outputs.signedReleaseFiles}}

#       - name: Echo APK
#         run: echo Signed APK FILE ${{steps.sign_app.outputs.signedReleaseFile}}
        
      - name: Release signed APK
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
            repo_token: "${{ secrets.TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: true
            title: "Release X"
            files: |
              ${{ steps.signed_files._0 }}
              ${{ steps.signed_files._1 }}
              ${{ steps.signed_files._2 }}
              ${{ steps.signed_files._3 }}
              ${{ steps.signed_files._4 }}
#              ${{steps.sign_app.outputs.signedReleaseFile}}

#       - name: Release signed APK
#         uses: MicahSphelele/action-publish-signed-apk@main
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
#           APP_FOLDER: app/phone
#           FILE_DIR: ${{steps.sign_app.outputs.signedReleaseFile}}
